[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../../crates/core" }  # ローカルのcoreライブラリを参照
video = { path = "../../crates/video" }
clap = { workspace = true }
anyhow = { workspace = true }
env_logger = { workspace = true }